### ISSUE TITLE
トップ画面でレイアウトシフトが発生しないようにする

### ISSUE THREAD

**Issue by eigoninaritai-naokichi** [Mouwf/FF14SNS#87]
## 概要
トップ画面でレイアウトシフトが発生しないようにする。

## 不具合内容
トップページに遷移した際、ユーザー画像の読み込み時にレイアウトシフトが発生する。
レイアウトシフトが発生している原因としてimgタグでデフォルトのサイズを指定していないのが原因だと思われる。

**Comment by ninnikuusagi** [comment]
対応した。
